# My First Google Colab set up

In [ ]:
print("hello world !!!")

hello world !!!

In [ ]:
!git config --global user.email "your_github_email@gmail.com"
!git config --global user.name "username"

In [ ]:
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

date_i_started_google_colab_in_colab_with_github = datetime.now(ZoneInfo('Asia/Kolkata'))

formatted_date = date_i_started_google_colab_in_colab_with_github.strftime("%Y-%m-%d %H:%M:%S")
print(formatted_date)

2026-04-13 09:40:49

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Building a Simple Linear regression model

In [ ]:
import kagglehub
path = kagglehub.dataset_download("shivamb/machine-predictive-maintenance-classification")

Using Colab cache for faster access to the 'machine-predictive-maintenance-classification' dataset.

In [ ]:
import os

for file in os.listdir(path):
  print("Files inside os path :: ", file)

Files inside os path ::  predictive_maintenance.csv

In [ ]:
import pandas as pd

df_predictive_maintanance = pd.read_csv(path + '/predictive_maintenance.csv')
df_predictive_maintanance.info()

#Insights from value_counts()-ing of 'Failure Type'
#1. The ratio of Non-Failure to Failure is

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Target                   10000 non-null  int64
 9   Failure Type             10000 non-null  object
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB

#Feature Engineering :

##Step 01 - EDA (Exploratory Data Analysis)

###1. Studying/Visuvalizing the raw data \ₙ
- **Numerical data** ->
- **Categorical data** ->
- **Missing values** ->
- **Outliers** ->

###2. Modifying/Cleaning the raw data
- Handle missing values - using mean, median, mode
- Handling imbalnced data - calculating the ratio of target variable
- handling outliers
- scaling down the data -> no idea as of now
- handling categoricL data -> one-hot encoding

In [ ]:
%ls

drive/  ml_as_beginner/  sample_data/

In [ ]:
df_predictive_maintanance.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000

In [ ]:
df_predictive_maintanance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Target                   10000 non-null  int64
 9   Failure Type             10000 non-null  object
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB

In [ ]:
df_predictive_maintanance.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Target', 'Failure Type'],
      dtype='object')

In [ ]:
df_product_column_data = df_predictive_maintanance['Product ID']
print(df_product_column_data)

0       M14860
1       L47181
2       L47182
3       L47183
4       L47184
         ...
9995    M24855
9996    H39410
9997    M24857
9998    H39412
9999    M24859
Name: Product ID, Length: 10000, dtype: object

# Sub section for Feature engineering

### This is created on sole purpose that the predictive maintenance used in above is a cleaned & structured dataset.

In [ ]:
import kagglehub
path = kagglehub.dataset_download("stephanmatzka/predictive-maintenance-dataset-ai4i-2020")

df_milling_machine_predictive_maintanence = pd.read_csv(path + '/ai4i2020.csv')
df_milling_machine_predictive_maintanence.head()

Using Colab cache for faster access to the 'predictive-maintenance-dataset-ai4i-2020' dataset.

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [ ]:
df_milling_machine_predictive_maintanence.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [ ]:
df_milling_machine_predictive_maintanence.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

# Starting New for Feature Engineering - APR1226

- Chose this way cause all the Kaggle datasets are cleaned version. Although this isn't raw dataset straight away from sensors, will be helpful in exploring feature engineering.

- update APR12261212 : this data set is about milling machine and contains data in matlib file. Hence proceeding with something direct.

In [ ]:
import scipy.io

data = scipy.io.loadmat('drive/MyDrive/mill.mat')
print(data.keys())
print(type(data))
print(len(data))

dict_keys(['__header__', '__version__', '__globals__', 'mill'])
<class 'dict'>
4

## The Following Dataset is for Turbo Engine Degradation Simulation

In [ ]:
import pandas as pd

columns = ['unit_number', 'time', 'op_settings_1', 'op_settings_2', 'op_settings_3', 's1', 's2', 's3', 's4', 's5', 's6', 's7',
    's8', 's9', 's10', 's11', 's12', 's13', 's14',
    's15', 's16', 's17', 's18', 's19', 's20', 's21']

path_turbo_engine_data = 'drive/MyDrive/Turbo Engine Degradation Simulation Data/'


df_turbo_engine_train = pd.read_csv(path_turbo_engine_data + 'train_FD001.txt', sep=r'\s+', header=None, names=columns)
df_turbo_engine_train.head()
# df_turbo_engine_train.info()
# df_turbo_engine_train.describe()
# df_turbo_engine_train.isna().sum()

,unit_number,time,op_settings_1,op_settings_2,op_settings_3,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

### Learnings APR12261638
(also need to check how to push only certain cells to github, to push only these cells to logs folder)

#### What and Why Predictive Maintenance - Stack from broadest to most specific

1. **Artificial Intelligence** - Everything that makes machines simulate intelligent behaviour.
2. **Machine Learning** - The subset of AI where machines learn from data instead of being explicitly programmed.
3. **Applied ML / Industrial AI** - ML applied to real physical systems — factories, engines, aircraft, power grids. This is where your career lives.
4. **Condition-Based Monitoring (CBM)** - The engineering discipline of watching machines continuously and making decisions based on their actual condition, not a fixed schedule. Predates ML — engineers were doing this with statistical control charts before algorithms existed.
5. **Predictive Maintenance (PdM)** - A specific strategy within CBM. Instead of "maintain every 3 months" or "maintain when broken," you maintain when the data says it's about to break. ML is what made this actually work at scale.

### Learning APR12261644

- EDM/ Feature Engineering cannot be done withour framing the problem statement. There are multiple way to look into data, many solvable things.
- Hence it is important to predict the problem statement.

### Learnings APR12261646

#### Time series data

- Each row is the same engine, one cycle later. Row 50 is the direct continuation of row 49. If you shuffle the rows, you destroy the entire meaning of the dataset. The past is everything. The trend is the signal.

#### Normal data

- Each row is a separate machine at a separate moment. Row 500 has nothing to do with row 499. You could shuffle all 10,000 rows randomly and your model would still train perfectly. The past doesn't exist. Only right now exists.

# Problem Statement 1 — Kaggle dataset [APR12262130]

Given a snapshot of sensor readings from an industrial machine at a single point in time — including temperature, rotational speed, torque, and tool wear — predict whether the machine will fail, and if so, classify the type of failure from five known failure modes: heat dissipation, power failure, overstrain, tool wear, or random failure.

1. **Type**: Multiclass classification
2. **Target**: Failure Type
3. **Challenge**: Severe class imbalance — 96.5% of rows are No Failure

# Problem Statement 2 — NASA turbofan dataset [APR12262130]

Given multivariate time series sensor readings recorded across the operational life of a turbofan aircraft engine — 21 sensors across multiple flight cycles — predict the Remaining Useful Life (RUL): the number of cycles remaining before the engine reaches failure.

1. **Type**: Regression
2. **Target**: RUL — to be engineered, not present in raw data
3. **Challenge**: No column headers, operating condition noise across 3 settings, 100 engines each with different lifespans